# Mice sleep

## Data reading, normalization/pre-processing, and seperation

In [1]:
import pandas as pd
import numpy as np

In [18]:
# The file is made up of the following structure:
# state : char (1 byte)
# bin : array[0..400] of single (array of 401 floats (4 bytes each))
# EEGv,EMGv,temp : single (4 bytes each)
# Make a pandas dataframe with the data with appropriate column names
# Create a dtype with the binary data format and the desired column names
file = './data/DBA10.smo'
dt = [('state', 'i1')]
for i in range(401):
    dt.append(('bin' + str(i), 'f4'))
dt.append(('EEGv', 'f4'))
dt.append(('EMGv', 'f4'))
dt.append(('temp', 'f4'))
dt = np.dtype(dt)
data = np.fromfile(file, dtype=dt)
# Or if you want to explicitly set the column names
df = pd.DataFrame.from_records(data)

# Normalize the state column as it is a categorical variable
df['state'] = df['state'].astype('category')
df['state'] = df['state'].cat.codes

# Keep only the first 2 out of 4 days of data
df = df[:int(len(df)/2)]

# Split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('state', axis=1), df['state'], test_size=0.2, random_state=42)


# Count number of occurrences of each state in the training set
y_train.value_counts()

8    4290
6    3694
7     643
2      11
0       2
Name: state, dtype: int64

## Feature Selection

In [3]:
# Selecting features
# For now we use all features



## Model building

### Model 1: Linear Regression

In [24]:
# Linear regression
from sklearn.linear_model import LinearRegression

# Train the model
lr = LinearRegression()
lr.fit(X_train, y_train)

# Predict the test set
y_pred = lr.predict(X_test)
# Evaluate the model

# Count the number of correct predictions (rounded to the nearest integer)
correct = 0
for i in range(len(y_pred)):
    if round(y_pred[i]) == y_test.iloc[i]:
        correct += 1
print('Accuracy: ' + str(correct / len(y_pred)))


Accuracy: 0.586574074074074


### Model 2: Random Forest

In [25]:
# Random forest
from sklearn.ensemble import RandomForestClassifier

# Train the model
rf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
rf.fit(X_train, y_train)

# Predict the test set
y_pred = rf.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))



Accuracy: 0.7240740740740741


### Model 3: Decision Tree

In [26]:
# Decision tree
from sklearn.tree import DecisionTreeClassifier

# Train the model
dt = DecisionTreeClassifier(random_state=0)
dt.fit(X_train, y_train)

# Predict the test set
y_pred = dt.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))


Accuracy: 0.7282407407407407


### Model 4: KNN

In [28]:

# KNN
from sklearn.neighbors import KNeighborsClassifier

# Train the model
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predict the test set
y_pred = knn.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))


Accuracy: 0.7494212962962963


### Model 5: Support Vector Machine

In [29]:

# SVM
from sklearn import svm

# Train the model
svm = svm.SVC()
svm.fit(X_train, y_train)

# Predict the test set
y_pred = svm.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))


Accuracy: 0.8530092592592593


### Model 6: Perceptron

In [27]:

# Perceptron
from sklearn.linear_model import Perceptron

# Train the model
ppn = Perceptron(max_iter=40, eta0=0.1, random_state=0)
ppn.fit(X_train, y_train)

# Predict the test set
y_pred = ppn.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

Accuracy: 0.4965277777777778


### Model 7: Neural Network

In [25]:
# Neural network

import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense

# Create the model
model = Sequential()
input_dim = X_train.shape[1]
print(input_dim)
model.add(Dense(300, input_dim=input_dim, activation='leaky_relu'))
model.add(Dense(70, activation='leaky_relu'))
model.add(Dense(30, activation='leaky_relu'))
model.add(Dense(10, activation='leaky_relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
opt = keras.optimizers.Adam(learning_rate=0.0001)
model.compile(loss='categorical_crossentropy', optimizer=opt)

# Train the model
batch_size = int(X_train.shape[0] / 100)
print(batch_size)
model.fit(X_train, y_train, epochs=200, batch_size=batch_size, verbose=0)

# Predict the test set
y_pred = model.predict(X_test)

# Evaluate the model with f1 score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
try:
    print('F1 score: ' + str(f1_score(y_test, y_pred, average='macro')))
except:
    # Accuracy 
    print(y_pred)
    print("Accuracy: " + str(accuracy_score(y_test, y_pred)))
    
# Confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))


404
345
270/270 [==============================] - 1s 3ms/step
F1 score: 0.0
[[   0    2    0    0    0    0]
 [   0    0    0    0    0    0]
 [   0   11    0    0    0    0]
 [   0 3694    0    0    0    0]
 [   0  643    0    0    0    0]
 [   0 4290    0    0    0    0]]


## Model Comparison